help:
    @just --list

build target:
  @if [ "{{target}}" = "flexmux" ]; then \
    cd libs/flexmux/frontend && pnpm install && pnpm run build; \
  elif [ -d "apps/{{target}}" ]; then \
    uvx --from build pyproject-build --installer=uv --outdir=dist --wheel apps/{{target}}; \
  elif [ -d "libs/{{target}}" ]; then \
    uvx --from build pyproject-build --installer=uv --outdir=dist --wheel libs/{{target}}; \
  else \
    echo "Error: Target '{{target}}' not found in apps/ or libs/"; \
    exit 1; \
  fi

run target:
  @if [ "{{target}}" = "flexmux" ]; then \
    uv run flexmux; \
  else \
    echo "Error: No run command defined for '{{target}}'"; \
    exit 1; \
  fi

# Generate .dockerignore from .gitignore. Kept as a generator (not a
# committed file) so .dockerignore stays in lockstep with .gitignore and
# never needs manual sync. The generator strips:
#   - `/.dockerignore` self-reference so offload's copy_untracked_files
#     picks up this gitignored-but-not-dockerignored file;
#   - `/libs/mngr/imbue/mngr/resources/Dockerfile.release` so offload
#     0.8.1's stricter staging phase can find the generated release
#     Dockerfile (0.7.x was laxer and didn't filter it out). The file is
#     gitignored because it's generated by _generate-release-dockerfile
#     right before offload runs; it must be visible to the offload build
#     context even though it's never committed.
[private]
_generate-dockerignore:
    grep -vE '^/?\.dockerignore$|^/libs/mngr/imbue/mngr/resources/Dockerfile\.release$' .gitignore > .dockerignore

# Generate Dockerfile.release from Dockerfile + Dockerfile.release.extras so the
# two Dockerfiles stay in sync without duplicating the base layers. Strips the
# trailing CMD from Dockerfile; the .extras file provides its own CMD.
[private]
_generate-release-dockerfile:
    #!/bin/bash
    set -ueo pipefail
    base=libs/mngr/imbue/mngr/resources/Dockerfile
    extras=libs/mngr/imbue/mngr/resources/Dockerfile.release.extras
    out=libs/mngr/imbue/mngr/resources/Dockerfile.release
    # Everything from the base Dockerfile up to (not including) the first CMD line.
    awk '/^CMD/{exit} {print}' "$base" > "$out"
    cat "$extras" >> "$out"

# Run tests on Modal via Offload
test-offload args="":
    #!/bin/bash
    set -ueo pipefail
    : "${MODAL_TOKEN_ID:?must be set}"
    : "${MODAL_TOKEN_SECRET:?must be set}"
    just _generate-dockerignore
    trap "rm -f .dockerignore" EXIT
    # offload 0.8.1 manages build context + image caching via git notes; no
    # tarballs, patches, or local cache-key files needed.
    offload -c offload-modal.toml {{args}} run || [[ $? -eq 2 ]]

    # Copy results to the main worktree so new worktrees inherit baselines via COPY mode.
    MAIN_WORKTREE=$(git worktree list --porcelain | head -1 | sed 's/^worktree //')
    if [ -f test-results/junit.xml ] && [ -n "$MAIN_WORKTREE" ] && [ "$MAIN_WORKTREE" != "$(pwd)" ]; then
        mkdir -p "$MAIN_WORKTREE/test-results"
        cp test-results/junit.xml "$MAIN_WORKTREE/test-results/junit.xml"
    fi

# Run acceptance tests on Modal via Offload
test-offload-acceptance args="":
    #!/bin/bash
    set -ueo pipefail
    : "${MODAL_TOKEN_ID:?must be set}"
    : "${MODAL_TOKEN_SECRET:?must be set}"
    just _generate-dockerignore
    trap "rm -f .dockerignore" EXIT
    # MODAL_IMAGE_BUILDER_VERSION=2025.06 is required for enable_docker support (Docker-in-Docker alpha).
    MODAL_IMAGE_BUILDER_VERSION=2025.06 offload -c offload-modal-acceptance.toml {{args}} run \
        --env "MODAL_TOKEN_ID=$MODAL_TOKEN_ID" \
        --env "MODAL_TOKEN_SECRET=$MODAL_TOKEN_SECRET" || [[ $? -eq 2 ]]

# Run release tests on Modal via Offload (with Docker-in-Docker)
test-offload-release args="":
    #!/bin/bash
    set -ueo pipefail
    : "${MODAL_TOKEN_ID:?must be set}"
    : "${MODAL_TOKEN_SECRET:?must be set}"
    : "${ANTHROPIC_API_KEY:?must be set}"

    # Regenerate Dockerfile.release from Dockerfile + Dockerfile.release.extras
    # so the two stay in sync.
    just _generate-release-dockerfile
    just _generate-dockerignore
    trap "rm -f .dockerignore" EXIT

    # MODAL_IMAGE_BUILDER_VERSION=2025.06 is required for enable_docker support (Docker-in-Docker alpha).
    MODAL_IMAGE_BUILDER_VERSION=2025.06 offload -c offload-modal-release.toml {{args}} run \
        --env "MODAL_TOKEN_ID=$MODAL_TOKEN_ID" \
        --env "MODAL_TOKEN_SECRET=$MODAL_TOKEN_SECRET" \
        --env "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY" \
        --env "IS_RELEASE=1" || [[ $? -eq 2 ]]

    # Copy results to the main worktree so new worktrees inherit baselines via COPY mode.
    MAIN_WORKTREE=$(git worktree list --porcelain | head -1 | sed 's/^worktree //')
    if [ -f test-results/junit.xml ] && [ -n "$MAIN_WORKTREE" ] && [ "$MAIN_WORKTREE" != "$(pwd)" ]; then
        mkdir -p "$MAIN_WORKTREE/test-results"
        cp test-results/junit.xml "$MAIN_WORKTREE/test-results/junit.xml"
    fi

# Xdist parallelism args for local dev recipes. Kept out of pyproject addopts
# so they don't leak into offload sandboxes (which run `-p no:xdist`).
_parallel := "-n 4 --dist=worksteal --max-worker-restart=0"
# Default mark filter for local unit + integration recipes. Kept out of
# pyproject addopts because it would collide with offload-modal-acceptance
# (which runs the opposite filter). A later -m on CLI overrides this.
_skip_acceptance_and_release := "-m 'not acceptance and not release'"

test-unit:
  uv run pytest {{_parallel}} {{_skip_acceptance_and_release}} --cov-report=html --ignore-glob="**/test_*.py" --cov-fail-under=36

test-integration:
  uv run pytest {{_parallel}} {{_skip_acceptance_and_release}} --cov-report=html --cov-fail-under=80

# Examples:
#   just test-quick
#   just test-quick libs/mngr
#   just test-quick libs/mngr/.../foo_test.py::test_bar
#   just test-quick "libs/mngr -m 'not tmux and not modal'"
# Note: pass complex argument strings (anything with spaces, like -m exprs)
# as ONE outer-quoted argument. Variadic {{args}} splits on whitespace
# and drops inner quoting, which would truncate `-m 'a and b'` to `-m a`.
# The recipe's default `-m 'not acceptance and not release'` can be
# overridden by supplying a `-m` inside args (later CLI -m wins).
# Fast local iteration: forwards args to pytest. No coverage, xdist-parallel.
test-quick args="":
  uv run pytest {{_parallel}} {{_skip_acceptance_and_release}} --no-cov {{args}}

test-acceptance:
  # when running these locally, we set the max duration super high just so that we don't fail (which makes it harder to see the errors)
  PYTEST_MAX_DURATION_SECONDS=600 uv run pytest {{_parallel}} --no-cov -m "no release"

test-release:
  # when running these locally, we set the max duration super high just so that we don't fail (which makes it harder to see the errors)
  PYTEST_MAX_DURATION_SECONDS=1200 uv run pytest {{_parallel}} --no-cov -m "acceptance or not acceptance"

# Generate test timings for pytest-split (run periodically to keep timings up to date. Runs all acceptance and release)
test-timings:
  # when running these locally, we set the max duration super high just so that we don't fail (which makes it harder to see the errors)
  PYTEST_MAX_DURATION_SECONDS=6000 uv run pytest --no-cov -n 0 -m "acceptance or not acceptance" --store-durations

# useful for running against a single test, regardless of how it is marked
test target:
  PYTEST_MAX_DURATION_SECONDS=600 uv run pytest -sv --no-cov -n 0 -m "acceptance or not acceptance" "{{target}}"

# Download the Tailwind Play CDN JS bundle for the minds desktop client.
# Idempotent and SHA-pinned via apps/minds/scripts/fetch_tailwind.sh -- the
# same script also runs automatically as a pnpm `postinstall` hook, so
# normally you do not need to invoke this recipe. Use it when you want to
# force-verify the file or after nuking the static/ dir.
minds-tailwind:
  bash apps/minds/scripts/fetch_tailwind.sh

# Sync vendor/mngr in forever-claude-template to this repo's HEAD and commit
# in FCT. Default FCT path is $HOME/project/forever-claude-template; override
# by passing a positional arg. Run from this repo on the branch you want to
# vendor (typically main); the recipe archives HEAD, replaces vendor/mngr/
# contents with that snapshot, and commits in FCT. Does not push. Aborts if
# FCT has any uncommitted changes -- resolve them first. The full release
# flow (release branches, push, merge to main) is the release-minds skill.
sync-vendor-mngr fct="$HOME/project/forever-claude-template":
    #!/bin/bash
    set -ueo pipefail
    fct="{{fct}}"
    if [ ! -d "$fct/vendor/mngr" ]; then
        echo "Error: $fct/vendor/mngr not found"
        exit 1
    fi
    if [ -n "$(git -C "$fct" status --porcelain)" ]; then
        echo "Error: $fct has uncommitted changes; resolve them first:"
        git -C "$fct" status --short
        exit 1
    fi
    branch=$(git rev-parse --abbrev-ref HEAD)
    short=$(git rev-parse --short HEAD)
    full=$(git rev-parse HEAD)
    tarball=$(mktemp)
    trap "rm -f $tarball" EXIT
    git archive --format=tar HEAD > "$tarball"
    cd "$fct/vendor/mngr"
    rm -rf ./* ./.[!.]*
    tar -xf "$tarball"
    cd "$fct"
    git add -A vendor/mngr/
    if git diff --cached --quiet -- vendor/mngr/; then
        echo "vendor/mngr already in sync with mngr ${short}; nothing to commit"
        exit 0
    fi
    git commit -m "Sync vendor/mngr to ${branch} (${short})" -m "Tracks ${full} in mngr."
    echo "Synced vendor/mngr to ${branch} (${short}). To publish: (cd $fct && git push origin ${branch})"


# === Modal deploy / minds iteration helpers ===
#
# All of these read per-env config from .minds/<env>/ (gitignored). The
# `<env>` name is whatever directory you have under .minds/ -- e.g.
# `production`, `staging`. The matching templates live in .minds/template/.

# Validate that .minds/<env>/*.sh files declare every key the templates
# declare, and print the modal-secret commands that `push-secrets` would
# run. Does NOT touch Modal. Run this first when you change a template
# or add a new per-env file.
push-secrets-dry-run env="production":
    uv run scripts/push_modal_secrets.py {{env}} --dry-run

# Upsert every per-env Modal secret declared in .minds/template/ for the
# given env. Reads .minds/<env>/<service>.sh and writes <service>-<env>
# secrets to Modal. Idempotent (uses --force).
push-secrets env="production":
    uv run scripts/push_modal_secrets.py {{env}}

# Deploy the remote_service_connector Modal app for the given env.
# Does NOT push secrets first -- run `just push-secrets <env>` if any
# .minds/<env>/*.sh files have changed since the last deploy.
deploy-connector env="production":
    bash scripts/deploy_remote_service_connector.sh {{env}}

# Deploy the modal_litellm proxy Modal app for the given env.
# Does NOT push secrets first -- run `just push-secrets <env>` if
# .minds/<env>/litellm.sh has changed since the last deploy.
deploy-litellm env="production":
    bash scripts/deploy_litellm.sh {{env}}

# Push every per-env secret then deploy every Modal app for the given
# env. Equivalent to push-secrets + deploy-connector + deploy-litellm.
deploy-all env="production": (push-secrets env) (deploy-connector env) (deploy-litellm env)

# Start the minds desktop client (electron) in dev mode.
# Sources .env (for ANTHROPIC_API_KEY etc.) and sets MINDS_WORKSPACE_*
# env vars so the create-form auto-fills "repository", "name", and
# "branch":
#   MINDS_WORKSPACE_GIT_URL = .external_worktrees/forever-claude-template/
#       (REQUIRED -- recipe fails if missing; run create-pool-hosts-dev
#       first to set it up).
#   MINDS_WORKSPACE_BRANCH  = the FCT worktree's current branch.
#   MINDS_WORKSPACE_NAME    = "mindtest".
# Override agent_name / branch via positional args:
#   just minds-start agent_name=foo branch=some-branch
# Refuses to start if another minds-start is already running in this
# worktree (PID file under /tmp keyed by worktree path). Use `just
# minds-stop` to kill the running instance first.
minds-start agent_name="mindtest" branch="":
    #!/bin/bash
    set -ueo pipefail
    pid_file="/tmp/minds-start-$(echo -n "$PWD" | sha1sum | cut -c1-12).pid"
    if [ -f "$pid_file" ]; then
        existing=$(cat "$pid_file" 2>/dev/null || echo "")
        if [ -n "$existing" ] && kill -0 "$existing" 2>/dev/null; then
            echo "error: minds-start is already running in this worktree (pid=$existing)" >&2
            echo "       run \`just minds-stop\` first." >&2
            exit 2
        fi
        rm -f "$pid_file"
    fi
    fct_wt="$(pwd)/.external_worktrees/forever-claude-template"
    if [ ! -e "$fct_wt/.git" ]; then
        echo "error: no FCT worktree at $fct_wt" >&2
        echo "       run \`just create-pool-hosts-dev <count>\` first to set it up," >&2
        echo "       or \`git worktree add\` it manually before re-running minds-start." >&2
        exit 2
    fi
    if [ -f .env ]; then
        set -a
        . .env
        set +a
    fi
    export MINDS_WORKSPACE_GIT_URL="$fct_wt"
    if [ -n "{{branch}}" ]; then
        export MINDS_WORKSPACE_BRANCH="{{branch}}"
    else
        export MINDS_WORKSPACE_BRANCH="$(git -C "$fct_wt" rev-parse --abbrev-ref HEAD)"
    fi
    export MINDS_WORKSPACE_NAME="{{agent_name}}"
    echo "MINDS_WORKSPACE_GIT_URL=$MINDS_WORKSPACE_GIT_URL"
    echo "MINDS_WORKSPACE_NAME=$MINDS_WORKSPACE_NAME"
    echo "MINDS_WORKSPACE_BRANCH=$MINDS_WORKSPACE_BRANCH"
    echo "$$" > "$pid_file"
    trap 'rm -f "$pid_file"' EXIT
    cd apps/minds && pnpm start

# Stop the minds desktop client started in this worktree by `just minds-start`.
# Reads the PID file written by minds-start and SIGTERMs the recipe shell;
# pnpm and electron follow on cascade. Idempotent (no-op if nothing running).
minds-stop:
    #!/bin/bash
    set -ueo pipefail
    pid_file="/tmp/minds-start-$(echo -n "$PWD" | sha1sum | cut -c1-12).pid"
    if [ ! -f "$pid_file" ]; then
        echo "no PID file at $pid_file -- nothing to stop"
        exit 0
    fi
    pid=$(cat "$pid_file")
    if [ -z "$pid" ] || ! kill -0 "$pid" 2>/dev/null; then
        echo "PID $pid in $pid_file is not running -- removing stale file"
        rm -f "$pid_file"
        exit 0
    fi
    echo "Stopping minds-start (pid=$pid)"
    kill "$pid"
    # Wait up to 10s for graceful shutdown, then SIGKILL.
    for i in $(seq 1 10); do
        if ! kill -0 "$pid" 2>/dev/null; then
            rm -f "$pid_file"
            exit 0
        fi
        sleep 1
    done
    echo "minds-start (pid=$pid) did not exit after SIGTERM; sending SIGKILL"
    kill -9 "$pid" 2>/dev/null || true
    rm -f "$pid_file"

# Build the minds desktop client distributable (slow; uses todesktop).
minds-build:
    cd apps/minds && pnpm build

# Sync this repo's mngr changes (and the FCT worktree's template state)
# into a running Docker agent's container, then restart the agent and the
# desktop client. Wraps apps/minds/scripts/propagate_changes by auto-
# discovering the agent's Docker SSH port (via `docker port`) and the
# minds-side SSH key (under MNGR_HOST_DIR's profiles/.../docker/.../keys/).
# Defaults MNGR_HOST_DIR to ~/.minds/mngr (production minds); pass
# mngr_host_dir=$HOME/.devminds/mngr if you're on a dev profile.
propagate-changes agent_name mngr_host_dir="$HOME/.minds/mngr":
    #!/bin/bash
    set -ueo pipefail
    agent_name="{{agent_name}}"
    mngr_host_dir="{{mngr_host_dir}}"
    container_name="mngr-${agent_name}-host"
    if ! docker inspect "$container_name" >/dev/null 2>&1; then
        echo "error: no docker container named '$container_name'" >&2
        echo "       run \`docker ps\` to see running containers" >&2
        exit 2
    fi
    port_mapping=$(docker port "$container_name" 22/tcp 2>/dev/null | head -1)
    if [ -z "$port_mapping" ]; then
        echo "error: container $container_name has no host port mapping for 22/tcp" >&2
        exit 2
    fi
    port="${port_mapping##*:}"
    keys=$(find "$mngr_host_dir/profiles" -path "*/docker/*/keys/docker_ssh_key" 2>/dev/null || true)
    if [ -z "$keys" ]; then
        echo "error: no docker_ssh_key found under $mngr_host_dir/profiles" >&2
        echo "       try mngr_host_dir=\$HOME/.devminds/mngr if you're on a dev profile," >&2
        echo "       or pass mngr_host_dir=<custom path>." >&2
        exit 2
    fi
    key_count=$(echo "$keys" | wc -l)
    if [ "$key_count" -gt 1 ]; then
        echo "error: multiple docker_ssh_key files found under $mngr_host_dir/profiles:" >&2
        echo "$keys" >&2
        echo "       narrow with mngr_host_dir=<more specific path>." >&2
        exit 2
    fi
    key="$keys"
    echo "Propagating changes to $agent_name (container=$container_name, port=$port, key=$key)"
    apps/minds/scripts/propagate_changes \
        --agent "$agent_name" \
        --user root --host 127.0.0.1 --port "$port" --key "$key"

# Pool host provisioning. Two recipes with different "what mngr code runs
# on the host?" semantics:
#  - create-pool-hosts-dev: maintains a PERSISTENT FCT worktree at
#    .external_worktrees/forever-claude-template/ on a branch named after
#    this repo's current mngr branch (so e.g. work on `mngr/imbue-auth`
#    here, see a parallel `mngr/imbue-auth` branch in FCT). On each run,
#    rsyncs THIS repo's working tree into vendor/mngr just long enough to
#    provision, then resets vendor/mngr to HEAD so any template-side
#    commits the user makes in the worktree stay free of mngr churn.
#  - create-pool-hosts: an EPHEMERAL temp checkout of FCT at a chosen
#    tag, with vendor/mngr left untouched. Whatever vendor/mngr is
#    committed at that tag is exactly what runs on the host. Cleaned up
#    on exit.

# Provision N Vultr pool hosts from a persistent FCT worktree, with this
# repo's WORKING TREE mngr code rsynced into vendor/mngr for the duration
# of provisioning. The worktree lives at .external_worktrees/forever-claude-template/
# and tracks a branch named the same as your current mngr branch, so you
# can iterate on template-side changes there without losing them between
# runs. After provisioning succeeds, vendor/mngr is reset to HEAD.
create-pool-hosts-dev count="1" env="production" version="v0.1.0" fct_repo="$HOME/project/forever-claude-template":
    #!/bin/bash
    set -ueo pipefail
    fct_repo="{{fct_repo}}"
    if [ ! -d "$fct_repo/.git" ]; then
        echo "error: FCT not found at $fct_repo (override fct_repo=...)" >&2
        exit 2
    fi
    if ! git -C "$fct_repo" rev-parse --verify origin/main >/dev/null 2>&1; then
        echo "error: $fct_repo has no origin/main (try git fetch origin)" >&2
        exit 2
    fi
    branch=$(git rev-parse --abbrev-ref HEAD)
    if [ "$branch" = "HEAD" ]; then
        echo "error: this repo is in detached HEAD; check out a branch first" >&2
        exit 2
    fi
    mkdir -p .external_worktrees
    fct_wt="$(pwd)/.external_worktrees/forever-claude-template"
    # Ensure the FCT worktree exists at $fct_wt on a branch named $branch.
    # Three cases: (1) no worktree, no FCT branch yet -- create both;
    # (2) no worktree, FCT branch already exists -- reuse the branch;
    # (3) worktree exists -- switch it to $branch (creating if needed).
    if [ -d "$fct_wt" ] && git -C "$fct_wt" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        cur_branch=$(git -C "$fct_wt" rev-parse --abbrev-ref HEAD)
        if [ "$cur_branch" != "$branch" ]; then
            if git -C "$fct_wt" rev-parse --verify "refs/heads/$branch" >/dev/null 2>&1; then
                git -C "$fct_wt" checkout "$branch"
            else
                git -C "$fct_wt" checkout -b "$branch" origin/main
            fi
        fi
    else
        if [ -e "$fct_wt" ]; then rm -rf "$fct_wt"; fi
        if git -C "$fct_repo" rev-parse --verify "refs/heads/$branch" >/dev/null 2>&1; then
            git -C "$fct_repo" worktree add "$fct_wt" "$branch"
        else
            git -C "$fct_repo" worktree add -b "$branch" "$fct_wt" origin/main
        fi
    fi
    target="$fct_wt/vendor/mngr"
    if [ ! -d "$target" ]; then
        echo "error: $target missing (FCT branch '$branch' lacks vendor/mngr)" >&2
        exit 2
    fi
    # Replace vendor/mngr with this repo's working tree (tracked + untracked-not-ignored).
    rm -rf "$target"
    mkdir -p "$target"
    tarball=$(mktemp)
    trap 'rm -f "$tarball"' EXIT
    echo "Snapshotting working tree into $target"
    git ls-files -z -co --exclude-standard | tar --null -T - -cf "$tarball"
    tar -xf "$tarball" -C "$target"
    set -a
    . .minds/{{env}}/.env
    . .minds/{{env}}/neon.sh
    set +a
    uv run python apps/remote_service_connector/scripts/create_pool_hosts.py \
        --count {{count}} --version {{version}} \
        --management-public-key-file .minds/{{env}}/pool_management_key/id_ed25519.pub \
        --template-dir "$fct_wt"
    # On success: restore vendor/mngr to whatever's checked in for $branch
    # so the worktree stays "clean" wrt vendor/mngr and template-side
    # commits don't carry mngr churn. A failure above leaves vendor/mngr
    # in its rsynced state for debugging; re-run to overwrite.
    echo "Resetting $target to HEAD."
    git -C "$fct_wt" checkout HEAD -- vendor/mngr
    git -C "$fct_wt" clean -fdx vendor/mngr

# Provision N Vultr pool hosts from a TAGGED FCT release, untouched. The
# vendor/mngr that ships in that tag is what runs on the host; this
# recipe never modifies vendor/mngr. Defaults to the most recent FCT tag
# whose tree contains vendor/mngr/ (older FCT tags predate that layout
# and are skipped). Pass `fct_tag=<tag>` to pin to a specific tag.
create-pool-hosts count="1" env="production" version="v0.1.0" fct_tag="" fct_repo="$HOME/project/forever-claude-template":
    #!/bin/bash
    set -ueo pipefail
    fct_repo="{{fct_repo}}"
    if [ ! -d "$fct_repo/.git" ]; then
        echo "error: FCT not found at $fct_repo (override fct_repo=...)" >&2
        exit 2
    fi
    fct_tag="{{fct_tag}}"
    if [ -z "$fct_tag" ]; then
        # Most recent tag (by version sort) whose tree contains vendor/mngr.
        for t in $(git -C "$fct_repo" tag --sort=-version:refname); do
            if git -C "$fct_repo" ls-tree -d "$t" vendor/mngr 2>/dev/null | grep -q .; then
                fct_tag="$t"
                break
            fi
        done
        if [ -z "$fct_tag" ]; then
            echo "error: no FCT tag with vendor/mngr/ in its tree." >&2
            echo "       Tag a commit that has vendor/mngr/, or pass fct_tag=<tag>." >&2
            exit 2
        fi
        echo "Defaulting to most recent FCT tag with vendor/mngr: $fct_tag"
    fi
    if ! git -C "$fct_repo" rev-parse --verify "${fct_tag}^{commit}" >/dev/null 2>&1; then
        echo "error: '$fct_tag' is not a known git ref in $fct_repo" >&2
        exit 2
    fi
    if ! git -C "$fct_repo" ls-tree -d "$fct_tag" vendor/mngr 2>/dev/null | grep -q .; then
        echo "error: FCT tag '$fct_tag' does not contain vendor/mngr/" >&2
        exit 2
    fi
    mkdir -p .external_worktrees
    fct_temp="$(pwd)/.external_worktrees/forever-claude-template-strict-$$-$(date +%s)"
    cleanup() {
        git -C "$fct_repo" worktree remove --force "$fct_temp" 2>/dev/null || rm -rf "$fct_temp"
    }
    trap cleanup EXIT
    echo "Creating temp FCT worktree at $fct_tag in $fct_temp"
    git -C "$fct_repo" worktree add --detach "$fct_temp" "$fct_tag"
    set -a
    . .minds/{{env}}/.env
    . .minds/{{env}}/neon.sh
    set +a
    uv run python apps/remote_service_connector/scripts/create_pool_hosts.py \
        --count {{count}} --version {{version}} \
        --management-public-key-file .minds/{{env}}/pool_management_key/id_ed25519.pub \
        --template-dir "$fct_temp"

# Destroy and remove every host in the pool with status='released'.
# Sources .minds/<env>/neon.sh for DATABASE_URL.
cleanup-pool-hosts env="production":
    #!/bin/bash
    set -ueo pipefail
    set -a
    . .minds/{{env}}/neon.sh
    set +a
    uv run python apps/remote_service_connector/scripts/cleanup_released_hosts.py \
        --database-url "$DATABASE_URL"
