"""Interface for Cloudflare API operations."""

from typing import Any
from typing import Protocol

from imbue.cloudflare_forwarding.primitives import CloudflareDnsRecordId
from imbue.cloudflare_forwarding.primitives import CloudflareTunnelId


class CloudflareClientInterface(Protocol):
    """Protocol for Cloudflare API operations used by ForwardingService."""

    def create_tunnel(self, name: str) -> dict[str, Any]: ...

    def list_tunnels(self, name_prefix: str = "") -> list[dict[str, Any]]: ...

    def get_tunnel_by_name(self, name: str) -> dict[str, Any] | None: ...

    def get_tunnel_token(self, tunnel_id: CloudflareTunnelId) -> str: ...

    def delete_tunnel(self, tunnel_id: CloudflareTunnelId) -> None: ...

    def get_tunnel_configuration(self, tunnel_id: CloudflareTunnelId) -> dict[str, Any]: ...

    def put_tunnel_configuration(self, tunnel_id: CloudflareTunnelId, config: dict[str, Any]) -> None: ...

    def create_cname_record(self, name: str, target: str) -> dict[str, Any]: ...

    def list_dns_records(self, name: str = "") -> list[dict[str, Any]]: ...

    def delete_dns_record(self, record_id: CloudflareDnsRecordId) -> None: ...
