from pathlib import Path
from typing import Final

from imbue.mngr import hookimpl
from imbue.mngr.config.data_types import MngrContext
from imbue.mngr.config.data_types import ProviderInstanceConfig
from imbue.mngr.errors import MngrError
from imbue.mngr.interfaces.provider_backend import ProviderBackendInterface
from imbue.mngr.interfaces.provider_instance import ProviderInstanceInterface
from imbue.mngr.primitives import ProviderBackendName
from imbue.mngr.primitives import ProviderInstanceName
from imbue.mngr.providers.deploy_utils import collect_provider_profile_files
from imbue.mngr.providers.docker.config import DockerProviderConfig
from imbue.mngr.providers.docker.instance import DockerProviderInstance

DOCKER_BACKEND_NAME: Final[ProviderBackendName] = ProviderBackendName("docker")

# SSH key and host key file names stored in the docker provider's profile directory.
# These are generated by load_or_create_ssh_keypair() and should not be baked into deployment images.
# Note that it is ok to include the host keys, since those are already present remotely (that's the whole point)
_DOCKER_EXCLUDED_PROFILE_FILES: Final[frozenset[str]] = frozenset(
    {
        "docker_ssh_key",
        "docker_ssh_key.pub",
        "known_hosts",
    }
)


class DockerProviderBackend(ProviderBackendInterface):
    """Backend for creating Docker container provider instances.

    The Docker provider backend creates provider instances that manage Docker
    containers as hosts. Each container runs sshd and is accessed via SSH/pyinfra.
    """

    @staticmethod
    def get_name() -> ProviderBackendName:
        return DOCKER_BACKEND_NAME

    @staticmethod
    def get_description() -> str:
        return "Runs agents in Docker containers with SSH access"

    @staticmethod
    def get_config_class() -> type[ProviderInstanceConfig]:
        return DockerProviderConfig

    @staticmethod
    def get_build_args_help() -> str:
        return "Build args are passed directly to 'docker build'. Run 'docker build --help' for details."

    @staticmethod
    def get_start_args_help() -> str:
        return "Start args are passed directly to 'docker run'. Run 'docker run --help' for details."

    @staticmethod
    def build_provider_instance(
        name: ProviderInstanceName,
        config: ProviderInstanceConfig,
        mngr_ctx: MngrContext,
    ) -> ProviderInstanceInterface:
        """Build a Docker provider instance."""
        if not isinstance(config, DockerProviderConfig):
            raise MngrError(f"Expected DockerProviderConfig, got {type(config).__name__}")
        host_dir = config.host_dir if config.host_dir is not None else Path("/mngr")
        return DockerProviderInstance(
            name=name,
            host_dir=host_dir,
            mngr_ctx=mngr_ctx,
            config=config,
        )


@hookimpl
def register_provider_backend() -> tuple[type[ProviderBackendInterface], type[ProviderInstanceConfig]]:
    """Register the Docker provider backend."""
    return (DockerProviderBackend, DockerProviderConfig)


@hookimpl
def get_files_for_deploy(
    mngr_ctx: MngrContext,
    include_user_settings: bool,
    include_project_settings: bool,
    repo_root: Path,
) -> dict[Path, Path | str]:
    """Include docker provider profile files, excluding SSH keypairs.

    SSH keypairs (docker_ssh_key, host_key, and their .pub companions) and
    known_hosts are excluded because they are environment-specific secrets.
    The deployed environment generates fresh keypairs via
    load_or_create_ssh_keypair().
    """
    if not include_user_settings:
        return {}
    return collect_provider_profile_files(mngr_ctx, "docker", _DOCKER_EXCLUDED_PROFILE_FILES)
